#include <stdint.h>

#define KEYBOARD_REG (*(volatile uint8_t*)0x80500000)

#define k_SPACE                   0
#define k_EXCLAMATION             1
#define k_QUOTE                   2
#define k_HASH                    3
#define k_DOLLAR                  4
#define k_PERCENT                 5
#define k_AMPERSAND               6
#define k_APOSTROPHE              7
#define k_L_PARENTHESIS           8
#define k_R_PARENTHESIS           9
#define k_ASTERISK                10
#define k_PLUS                    11
#define k_COMMA                   12
#define k_HYPHEN                  13
#define k_PERIOD                  14
#define k_SLASH                   15
#define k_ZERO                    16
#define k_ONE                     17
#define k_TWO                     18
#define k_THREE                   19
#define k_FOUR                    20
#define k_FIVE                    21
#define k_SIX                     22
#define k_SEVEN                   23
#define k_EIGHT                   24
#define k_NINE                    25
#define k_COLON                   26
#define k_SEMICOLON               27
#define k_LESS                    28
#define k_EQUAL                   29
#define k_GREATER                 30
#define k_QUESTION                31
#define k_AT                      32
#define k_A                       33
#define k_B                       34
#define k_C                       35
#define k_D                       36
#define k_E                       37
#define k_F                       38
#define k_G                       39
#define k_H                       40
#define k_I                       41
#define k_J                       42
#define k_K                       43
#define k_L                       44
#define k_M                       45
#define k_N                       46
#define k_O                       47
#define k_P                       48
#define k_Q                       49
#define k_R                       50
#define k_S                       51
#define k_T                       52
#define k_U                       53
#define k_V                       54
#define k_W                       55
#define k_X                       56
#define k_Y                       57
#define k_Z                       58
#define k_L_BRACKET               59
#define k_BACKSLASH               60
#define k_R_BRACKET               61
#define k_CARET                   62
#define k_UNDERSCORE              63
#define k_BACKTICK                64
#define k_a                       65
#define k_b                       66
#define k_c                       67
#define k_d                       68
#define k_e                       69
#define k_f                       70
#define k_g                       71
#define k_h                       72
#define k_i                       73
#define k_j                       74
#define k_k                       75
#define k_l                       76
#define k_m                       77
#define k_n                       78
#define k_o                       79
#define k_p                       80
#define k_q                       81
#define k_r                       82
#define k_s                       83
#define k_t                       84
#define k_u                       85
#define k_v                       86
#define k_w                       87
#define k_x                       88
#define k_y                       89
#define k_z                       90
#define k_L_BRACE                 91
#define k_PIPE                    92
#define k_R_BRACE                 93
#define k_TILDE                   94
#define k_DELETE                  95
#define k_CAPS                    96
#define k_BACKSPACE               97

#define k_NONE                    0xFF

uint8_t keyboard_read();